general: 
  logdir: logs/
  exp_name: test_single_mask
  TIMEIT: True
  dev: false
  skip: 1
  enable_amp: false
  checkpoint_dir: checkpoints/
  lr: 0.0001
  batch_size: 16
  num_workers: 8
  weight_decay: 0.005
  val_freq: 1
  epochs: 500
  resume: null
  distributed: false
  save_output: false
  stage: ['flyingthings', 'driving', 'monkaa']
  num_epochs: 100
  max_disp: 400
  val_stage: ['eth3d', 'middlebury', 'kitti']

model:
  feature_dim_s16: 128
  context_dim_s16: 64
  iter_context_dim_s16: 64
  feature_dim_s8: 128
  context_dim_s8: 64
  iter_context_dim_s8: 64
  feature_dim_s1: 128
  upsample_method: "raft"
  max_disparity: 192